- name: "Checkout repository"
  git:
    repo: https://github.com/RNiveau/nokiaToFitbitBridge
    dest: /home/pi/nokiaToFitbitBridge

- name: "Install package"
  npm:
    path: /home/pi/nokiaToFitbitBridge
    state: present

- name: "Create cron about bridge"
  cron:
    name: "nokiaToFitbitBridge"
    special_time: hourly
    job: /usr/bin/node /home/pi/nokiaToFitbitBridge/bridge_nokia_fitbit.js
    user: "{{ansible_user}}"

- name: "Create cron about bridge"
  cron:
    name: "Watch water"
    special_time: hourly
    job: /usr/bin/node /home/pi/nokiaToFitbitBridge/fitbit_water_watch.js
    user: "{{ansible_user}}"

- name: "File for config"
  template:
    src: templates/config.json.j2
    dest: /home/pi/nokiaToFitbitBridge/config.json
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: 0644
