#Activate wifi
#https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md
---
- name: "Provisioning raspberry media center"
  hosts: pi

  roles: 
    - {role: base_raspberry_config}
    - {role: update_repositories}
    - {role: install_kodi, tags: 'kodi'}
    - {role: mount_timecapsule, tags: 'kodi'}
#    - install_homekit-bridge
    - {role: install_git, tags: 'code'}
    - {role: python, tags: 'code'}
    - {role: nodejs, tags: 'code'}
    - {role: nokia_to_fitbit_bridge, tags: 'code'}
    - {role: meal_management, tags: 'code'}
    - {role: install_avahi}
