---
- name: "Provisioning raspberry media center"
  hosts: pi

  roles: 
    - base_raspberry_config
    - update_repositories
    - install_kodi
    - mount_timecapsule
    - install_nvm
    - install_homekit-bridge