---
- name: "Mount timecapsule"
  mount:
    path: "{{timecapsule_path}}"
    src: "{{timecapsule_src}}"
    fstype: cifs
    opts: username={{timecapsuleUsername}},password={{timecapsuleUserPassword}},rw,uid=1000,iocharset=utf8,sec=ntlm 0 0
    state: mounted
  become: true