---
- name: "Mount timecapsule"
  mount:
    name: "{{timecapsule_path}}"
    src: "{{timecapsule_src}}"
    fstype: cifs
    opts: username={{timecapsuleUsername}},password={{timecapsulePassword}},rw,uid=1000,iocharset=utf8,sec=ntlm
    state: mounted
  become: true