- name: "Install system dependencies"
  package:
    name: libavahi-compat-libdnssd-dev
    state: present
  become: true

- name: "Install npm dependencies"
  shell: bash -lc "npm install -g homebridge"
  register: npm_install

- fail:
    msg: "{{npm_install.stderr}}"
  when: npm_install.rc != 0