version: "2"
services:
  api:
    container_name: api
    image: rniveau/crypto-wallet:api
    links:
    - mongo
    ports:
    - 8080:8080
    volumes:
    - /etc/crypto-wallet/config.yaml:/etc/crypto-wallet/config.yaml
  mongo:
    container_name: mongo
    image: bitnami/mongodb:3.6.8
    volumes:
    - /var/crypto-wallet-mongo:/bitnami/mongodb/data/db/
