---
- name: "Install kodi"
  apt:
    name: kodi
    state: latest
    force: yes
  become: true

- name: "Create kodi directory"
  file: 
    path: /home/pi/.kodi/userdata
    state: directory
    recurse: yes

- name: "Add sources file"
  copy:
     src: sources.xml
     dest: /home/pi/.kodi/userdata/sources.xml
     mode: "0755"

- name: "Create videos files"
  file: 
    path: /home/pi/videos
    state: directory