- name: Install insserv
  package:
    name: insserv
    state: latest
  become: true

- name: Install avahi
  package:
    name: avahi-daemon
    state: latest
  become: true

- name: Copy avahi configuration
  template:
    src: avahi.conf.j2
    dest: /etc/avahi/avahi-daemon.conf
    owner: root
    group: root
  become: true
  notify: Restart avahi