- name: Install insserv
  package:
    name: insserv
    state: latest
  become: true

- name: Install avahi
  package:
    name: avahi-daemon
    state: latest
  become: true

- name: Restart avahi 
  service:
    name: avahi-daemon
    state: restarted
  become: true